### PR TITLE
Session and socket fixes

### LINKED ISSUE #12: Change session store
https://github.com/expressjs/session/blob/master/README.md#compatible-session-stores

### PR DESCRIPTION
**Pull request by cnasikas**
Fix #12

### CODE REVIEW

File: api/ws-server.js [hunk 1]
```diff
@@ -20,7 +20,14 @@ const setupWss = async (server, sessionStore) => {
   io.on('connection', (client) => {
     logger.info(`Web client connected: ID: ${client.id}`)
     const user = { ...client.request.user.dataValues }
-    clients[user.id] = { socketID: client.id, user }
+
+    if (clients[user.id] && clients[user.id].sockets) {
+      clients[user.id].sockets.push(client.id)
+    } else {
+      clients[user.id] = { sockets: [client.id], user }
+    }
```
Comment (dionyziz) [inline api/ws-server.js:26]: Better written as:

```
if (!clients[user.id]) {
  clients[user.id] = { sockets: [], user }
}
clients[user.id].sockets.push(client.id)
```

**Review by dionyziz — APPROVED** [review]

File: api/ws-server.js (hunk 1 above)
Comment (OrfeasLitos) [reply api/ws-server.js:26]: Are we certain that if `clients[user.id]` exists, then also `.sockets` exists?

Comment (dionyziz) [reply api/ws-server.js:26]: Yes – the entry is only created at this point and `sockets` is never removed from it.
